exclude:
  images
  assets
  examples
  intro
sidebar:
  grandparent: fa-bars
  parent: fa-caret-down
  current: fa-caret-right
  sub: fa-plus
  sibling: fa-plus
  external: fa-share
next:
  icon: fa-forward
previous:
  icon: fa-backward
